with-expecter: true
packages:
  github.com/jha-captech/user-microservice/internal/handlers:
    config:
      filename: "{{.InterfaceName | snakecase }}.go"
      dir: "{{.InterfaceDir}}/mock"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mock"
      inpackage: false
    interfaces:
      createUserServicer:
      deleteUserServicer:
      fetchUserServicer:
      listUserServicer:
      updateUserServicer:
      sLogger: