# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: