// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	models "github.com/jha-captech/user-microservice/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockdeleteUserServicer is an autogenerated mock type for the deleteUserServicer type
type MockdeleteUserServicer struct {
	mock.Mock
}

type MockdeleteUserServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdeleteUserServicer) EXPECT() *MockdeleteUserServicer_Expecter {
	return &MockdeleteUserServicer_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function with given fields: ID
func (_m *MockdeleteUserServicer) DeleteUser(ID int) error {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdeleteUserServicer_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockdeleteUserServicer_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ID int
func (_e *MockdeleteUserServicer_Expecter) DeleteUser(ID interface{}) *MockdeleteUserServicer_DeleteUser_Call {
	return &MockdeleteUserServicer_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ID)}
}

func (_c *MockdeleteUserServicer_DeleteUser_Call) Run(run func(ID int)) *MockdeleteUserServicer_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockdeleteUserServicer_DeleteUser_Call) Return(_a0 error) *MockdeleteUserServicer_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdeleteUserServicer_DeleteUser_Call) RunAndReturn(run func(int) error) *MockdeleteUserServicer_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUser provides a mock function with given fields: ID
func (_m *MockdeleteUserServicer) FetchUser(ID int) (models.User, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.User, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) models.User); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdeleteUserServicer_FetchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUser'
type MockdeleteUserServicer_FetchUser_Call struct {
	*mock.Call
}

// FetchUser is a helper method to define mock.On call
//   - ID int
func (_e *MockdeleteUserServicer_Expecter) FetchUser(ID interface{}) *MockdeleteUserServicer_FetchUser_Call {
	return &MockdeleteUserServicer_FetchUser_Call{Call: _e.mock.On("FetchUser", ID)}
}

func (_c *MockdeleteUserServicer_FetchUser_Call) Run(run func(ID int)) *MockdeleteUserServicer_FetchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockdeleteUserServicer_FetchUser_Call) Return(_a0 models.User, _a1 error) *MockdeleteUserServicer_FetchUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdeleteUserServicer_FetchUser_Call) RunAndReturn(run func(int) (models.User, error)) *MockdeleteUserServicer_FetchUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdeleteUserServicer creates a new instance of MockdeleteUserServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdeleteUserServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdeleteUserServicer {
	mock := &MockdeleteUserServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
