// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// MockSLogger is an autogenerated mock type for the sLogger type
type MockSLogger struct {
	mock.Mock
}

type MockSLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSLogger) EXPECT() *MockSLogger_Expecter {
	return &MockSLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: msg, args
func (_m *MockSLogger) Debug(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockSLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockSLogger_Expecter) Debug(msg interface{}, args ...interface{}) *MockSLogger_Debug_Call {
	return &MockSLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockSLogger_Debug_Call) Run(run func(msg string, args ...interface{})) *MockSLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSLogger_Debug_Call) Return() *MockSLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSLogger_Debug_Call) RunAndReturn(run func(string, ...interface{})) *MockSLogger_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: msg, args
func (_m *MockSLogger) Error(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockSLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockSLogger_Expecter) Error(msg interface{}, args ...interface{}) *MockSLogger_Error_Call {
	return &MockSLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockSLogger_Error_Call) Run(run func(msg string, args ...interface{})) *MockSLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSLogger_Error_Call) Return() *MockSLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSLogger_Error_Call) RunAndReturn(run func(string, ...interface{})) *MockSLogger_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: msg, args
func (_m *MockSLogger) Info(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockSLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockSLogger_Expecter) Info(msg interface{}, args ...interface{}) *MockSLogger_Info_Call {
	return &MockSLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockSLogger_Info_Call) Run(run func(msg string, args ...interface{})) *MockSLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSLogger_Info_Call) Return() *MockSLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSLogger_Info_Call) RunAndReturn(run func(string, ...interface{})) *MockSLogger_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function with given fields: msg, args
func (_m *MockSLogger) Warn(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockSLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockSLogger_Expecter) Warn(msg interface{}, args ...interface{}) *MockSLogger_Warn_Call {
	return &MockSLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockSLogger_Warn_Call) Run(run func(msg string, args ...interface{})) *MockSLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSLogger_Warn_Call) Return() *MockSLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSLogger_Warn_Call) RunAndReturn(run func(string, ...interface{})) *MockSLogger_Warn_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSLogger creates a new instance of MockSLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSLogger {
	mock := &MockSLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
