// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	models "github.com/jha-captech/user-microservice/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserLister is an autogenerated mock type for the userLister type
type MockUserLister struct {
	mock.Mock
}

type MockUserLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserLister) EXPECT() *MockUserLister_Expecter {
	return &MockUserLister_Expecter{mock: &_m.Mock}
}

// ListUsers provides a mock function with given fields:
func (_m *MockUserLister) ListUsers() ([]models.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserLister_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserLister_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
func (_e *MockUserLister_Expecter) ListUsers() *MockUserLister_ListUsers_Call {
	return &MockUserLister_ListUsers_Call{Call: _e.mock.On("ListUsers")}
}

func (_c *MockUserLister_ListUsers_Call) Run(run func()) *MockUserLister_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserLister_ListUsers_Call) Return(_a0 []models.User, _a1 error) *MockUserLister_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserLister_ListUsers_Call) RunAndReturn(run func() ([]models.User, error)) *MockUserLister_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserLister creates a new instance of MockUserLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserLister {
	mock := &MockUserLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
