AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  UserMicroservice

  Sample API using AWS Lambda. Provides CRUD functionality for a user microservice. 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: bootstrap
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Timeout: 5
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        ENV: !Ref ENV
        DATABASE_CONTAINER_NAME: !Ref DATABASE_CONTAINER_NAME
        DATABASE_NAME: !Ref DATABASE_NAME
        DATABASE_USER: !Ref DATABASE_USER
        DATABASE_PASSWORD: !Ref DATABASE_PASSWORD
        DATABASE_HOST: !Ref DATABASE_HOST
        DATABASE_PORT: !Ref DATABASE_PORT
        DATABASE_CONNECTION_RETRY: !Ref DATABASE_CONNECTION_RETRY

Resources:

  # ── Lambdas ─────────────────────────────────────────────────────────────────────────────────────
  
  UserMicroserviceList:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/lambda/list/
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /api/user
            Method: GET

  UserMicroserviceFetch:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/lambda/fetch/
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /api/user/{ID}
            Method: GET

  UserMicroserviceUpdate:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/lambda/update/
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /api/user/{ID}
            Method: PUT

  UserMicroserviceCreate:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/lambda/create/
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /api/user
            Method: POST

  UserMicroserviceDelete:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/lambda/delete/
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /api/user/{ID}
            Method: DELETE